import { Game } from './Game';

export const games: Game[] = [
  {
    name: 'Red Rising',
    genre: 'Strategy',
    width: 296,
    height: 296,
    depth: 70,
    publisher: 'Stonemaier Games',
  },
  {
    name: 'Catan',
    genre: 'Strategy',
    width: 110,
    height: 206,
    depth: 85,
    publisher: 'KOSMOS',
  },
  {
    name: 'Just One',
    genre: 'Family',
    width: 150,
    height: 200,
    depth: 60,
    publisher: 'Repos Production',
  },
  {
    name: 'Furnace',
    genre: 'Economy',
    width: 300,
    height: 300,
    depth: 100,
    publisher: 'Hobby World',
  },
  {
    name: 'Terraforming Mars',
    genre: 'Strategy',
    width: 300,
    height: 250,
    depth: 200,
    publisher: 'FryxGames',
  },
  {
    name: 'Tapestry',
    genre: 'Strategy',
    width: 300,
    height: 300,
    depth: 80,
    publisher: 'Stonemaier Games',
  },
  {
    name: 'Steampunk Rally Fusion',
    genre: 'Family',
    width: 250,
    height: 250,
    depth: 70,
    publisher: 'Roxley Games',
  },
  {
    name: 'Radlands',
    genre: 'Strategy',
    width: 50,
    height: 100,
    depth: 30,
    publisher: 'Roxley Games',
  },
  {
    name: '7 Wonders',
    genre: 'Strategy',
    width: 300,
    height: 250,
    depth: 200,
    publisher: 'Repos Production',
  },
  {
    name: 'Scythe',
    genre: 'Strategy',
    width: 300,
    height: 365,
    depth: 98,
    publisher: 'Stonemaier Games',
  },
  {
    name: 'Top Ten',
    genre: 'Family',
    width: 200,
    height: 250,
    depth: 200,
    publisher: 'Cocktail Games',
  },
  {
    name: 'Ark Nova',
    genre: 'Economy',
    width: 300,
    height: 300,
    depth: 100,
    publisher: 'Feuerland Spiele',
  },
  {
    name: 'Dune Imperium',
    genre: 'Strategy',
    width: 300,
    height: 250,
    depth: 200,
    publisher: 'Dire Wolf',
  },
  {
    name: 'Regicide',
    genre: 'Strategy',
    width: 70,
    height: 100,
    depth: 20,
    publisher: 'Devir',
  },
  {
    name: `Time's Up`,
    genre: 'Family',
    width: 200,
    height: 250,
    depth: 200,
    publisher: 'R&R Games',
  },
  {
    name: 'Food Chain Magnate',
    genre: 'Economy',
    width: 300,
    height: 300,
    depth: 100,
    publisher: 'Splotter Spellen',
  },
  {
    name: 'Dice Throne Marvel Volume 1',
    genre: 'Strategy',
    width: 300,
    height: 200,
    depth: 80,
    publisher: 'Roxley Games',
  },
];
